[env:esp32-c3-supermini]
platform = espressif32@6.4.0
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

board_build.flash_mode = qio

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_LOOP_STACK_SIZE=16384

lib_deps =
    nrf24/RF24 @ 1.6.0
